#!/bin/python3

from rsa import generatekey, crypt_rsa, decrypt_rsa
import argparse
from utils import flatten, chunks, show_hex
from xor import apply_xor
from aes import encrypt_aes, decrypt_aes
from sys import stdin
from os import set_blocking

def hex_int(x):
    return int(x, 16)

def parsearg():
    parser = argparse.ArgumentParser(usage='mypgd [-xor | -aes | -rsa] [-c | -d] [-b] KEY\nthe MESSAGE is read from standard input', description='MyPGP - encryption/decryption tool')

    algorithm_group = parser.add_argument_group("Encryption Algorithm")
    algorithm_group.add_argument("-xor", action="store_true", help="Use Xor encryption")
    algorithm_group.add_argument("-aes", action="store_true", help="Use Aes encryption")
    algorithm_group.add_argument("-rsa", action="store_true", help="Use Rsa encryption")

    mode_group = parser.add_argument_group("Encryption Mode")
    mode_group.add_argument("-c", action="store_true", help="Encrypt")
    mode_group.add_argument("-d", action="store_true", help="Decrypt")

    parser.add_argument("-b", action="store_true", help="Use batch mode")
    parser.add_argument("-g", nargs=2, metavar=("P", "Q"), type=hex_int,help="for RSA only: generate a public and private key\npair from the prime number P and Q")
    parser.add_argument("KEY", nargs='?', help="Encryption/Decryption key")

    args = parser.parse_args()

    if not (args.xor or args.aes or args.rsa):
        parser.error("You must specify an encryption algorithm: -xor, -aes, or -rsa")
    if (args.xor and (args.aes or args.rsa)) or (args.aes and (args.xor or args.rsa)):
        parser.error("You can only select one encryption algorithm: -xor, -aes, or -rsa")
    if args.rsa and args.b:
        parser.error("You can not use -b with -rsa")
    if args.g and args.rsa == False:
        parser.error("You can not use -g without -rsa")
    if (not (args.c or args.d)) and (not args.g):
        parser.error("You must specify an encryption mode: -c (encrypt) or -d (decrypt)")
    if (args.c and args.d) and (not args.g):
        parser.error("You can only select one encryption mode: -c (encrypt) or -d (decrypt)")
    return args

def get_input(block_mode: bool, key: bytearray) -> bytearray:
    if block_mode:
        set_blocking(stdin.fileno(), False)
        message = stdin.read(len(key) * 2)
        set_blocking(stdin.fileno(), True)
    else:
        message = stdin.read()
    return flatten(message)

if __name__ == "__main__":
    try:
        args = parsearg()
    except SystemExit as e:
        if e.code == 2:
            exit(84)
        else:
            exit(e.code)
    if args.g:
        generatekey(args.g[0], args.g[1])
    if args.rsa and args.c:
        message = input()
        crypt_rsa(args.KEY, message)
    elif args.rsa and args.d:
        message = input()
        decrypt_rsa(args.KEY, message)
    key = flatten(args.KEY)
    if (args.xor):
        message = get_input(args.b, key)
        print(apply_xor(message, key))
    elif (args.aes):
        message = get_input(args.b, key)
        f = encrypt_aes if args.c else decrypt_aes
        print(''.join(show_hex(f(block, key)) for block in chunks(message, 16)))

